import pandas as pd
df=pd.read_csv(r"C:\Users\muska\OneDrive\muskan csf pdf\employee_grouping.csv")
print(df)
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Performance_Score"].max())
print(df.groupby("Department")["Salary"].min())
print(df.groupby("Department")["Projects_Completed"].sum())
print(df.groupby("Department")["Salary"].agg(["mean", "sum", "max", "min"]))
print(df[df["Performance_Score"] > 80])
print(df[df["Salary"] > 60000])
print(df[df["Department"] == "IT"])
a = df.groupby("Department")["Performance_Score"].mean()
print(a[a > 80])
print(df.groupby(["Department", "Gender"]).size())
print(df.loc[df.groupby("Department")["Salary"].idxmax()])